In [34]:
print("Jigsaw Events advertisement data practice as of 28/7/26")

Jigsaw Events advertisement data practice as of 28/7/26

In [1]:
print("Basic Panda data manipulation, filtering, grouping and sorting:")

Basic Panda data manipulation, filtering, grouping and sorting:

In [1]:
import pandas as pd

In [6]:
df = pd.read_csv("../data/advertisement.csv")
print(df)

          day  tickets_sold  event_views
0      Sunday             0           12
1      Monday             0           16
2     Tuesday             0            5
3   Wednesday             0            8
4    Thursday             0            2
5      Friday             0            4
6    Saturday             0           14
7      Sunday             9           35
8      Monday             2           10
9     Tuesday             0            6
10  Wednesday             0           22
11   Thursday             1           10
12     Friday             0           10
13   Saturday             0            2
14     Sunday             0            3
15     Monday             6           41
16    Tuesday             0            9

In [ ]:
df.head(10)

         day  tickets_sold  event_views
0     Sunday             0           12
1     Monday             0           16
2    Tuesday             0            5
3  Wednesday             0            8
4   Thursday             0            2
5     Friday             0            4
6   Saturday             0           14
7     Sunday             9           35
8     Monday             2           10
9    Tuesday             0            6

In [8]:
df.tail(5)

         day  tickets_sold  event_views
12    Friday             0           10
13  Saturday             0            2
14    Sunday             0            3
15    Monday             6           41
16   Tuesday             0            9

In [9]:
df.shape

(17, 3)

In [10]:
df.columns

Index(['day', 'tickets_sold', 'event_views'], dtype='str')

In [11]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 17 entries, 0 to 16
Data columns (total 3 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   day           17 non-null     str
 1   tickets_sold  17 non-null     int64
 2   event_views   17 non-null     int64
dtypes: int64(2), str(1)
memory usage: 540.0 bytes

In [12]:
df["day"]

0        Sunday
1        Monday
2       Tuesday
3     Wednesday
4      Thursday
5        Friday
6      Saturday
7        Sunday
8        Monday
9       Tuesday
10    Wednesday
11     Thursday
12       Friday
13     Saturday
14       Sunday
15       Monday
16      Tuesday
Name: day, dtype: str

In [13]:
df[["day","tickets_sold","event_views"]]

          day  tickets_sold  event_views
0      Sunday             0           12
1      Monday             0           16
2     Tuesday             0            5
3   Wednesday             0            8
4    Thursday             0            2
5      Friday             0            4
6    Saturday             0           14
7      Sunday             9           35
8      Monday             2           10
9     Tuesday             0            6
10  Wednesday             0           22
11   Thursday             1           10
12     Friday             0           10
13   Saturday             0            2
14     Sunday             0            3
15     Monday             6           41
16    Tuesday             0            9

In [14]:
df["event_views"] > 10

0      True
1      True
2     False
3     False
4     False
5     False
6      True
7      True
8     False
9     False
10     True
11    False
12    False
13    False
14    False
15     True
16    False
Name: event_views, dtype: bool

In [15]:
df[df["event_views"] > 10]

          day  tickets_sold  event_views
0      Sunday             0           12
1      Monday             0           16
6    Saturday             0           14
7      Sunday             9           35
10  Wednesday             0           22
15     Monday             6           41

In [16]:
df[df["event_views"] < 20]

          day  tickets_sold  event_views
0      Sunday             0           12
1      Monday             0           16
2     Tuesday             0            5
3   Wednesday             0            8
4    Thursday             0            2
5      Friday             0            4
6    Saturday             0           14
8      Monday             2           10
9     Tuesday             0            6
11   Thursday             1           10
12     Friday             0           10
13   Saturday             0            2
14     Sunday             0            3
16    Tuesday             0            9

In [17]:
df[df["tickets_sold"] <= 5]

          day  tickets_sold  event_views
0      Sunday             0           12
1      Monday             0           16
2     Tuesday             0            5
3   Wednesday             0            8
4    Thursday             0            2
5      Friday             0            4
6    Saturday             0           14
8      Monday             2           10
9     Tuesday             0            6
10  Wednesday             0           22
11   Thursday             1           10
12     Friday             0           10
13   Saturday             0            2
14     Sunday             0            3
16    Tuesday             0            9

In [18]:
df[df["day"] == "Saturday"]

         day  tickets_sold  event_views
6   Saturday             0           14
13  Saturday             0            2

In [19]:
df[(df["day"] == "Sunday") & (df["event_views"] > 10)]

      day  tickets_sold  event_views
0  Sunday             0           12
7  Sunday             9           35

In [20]:
df[(df["day"] == "Saturday") | (df["day"] == "Sunday")]

         day  tickets_sold  event_views
0     Sunday             0           12
6   Saturday             0           14
7     Sunday             9           35
13  Saturday             0            2
14    Sunday             0            3

In [21]:
df.sort_values("event_views", ascending=False)

          day  tickets_sold  event_views
15     Monday             6           41
7      Sunday             9           35
10  Wednesday             0           22
1      Monday             0           16
6    Saturday             0           14
0      Sunday             0           12
12     Friday             0           10
11   Thursday             1           10
8      Monday             2           10
16    Tuesday             0            9
3   Wednesday             0            8
9     Tuesday             0            6
2     Tuesday             0            5
5      Friday             0            4
14     Sunday             0            3
4    Thursday             0            2
13   Saturday             0            2

In [22]:
df.sort_values("tickets_sold", ascending=False)

          day  tickets_sold  event_views
7      Sunday             9           35
15     Monday             6           41
8      Monday             2           10
11   Thursday             1           10
0      Sunday             0           12
4    Thursday             0            2
3   Wednesday             0            8
1      Monday             0           16
2     Tuesday             0            5
5      Friday             0            4
6    Saturday             0           14
10  Wednesday             0           22
9     Tuesday             0            6
12     Friday             0           10
13   Saturday             0            2
14     Sunday             0            3
16    Tuesday             0            9

In [23]:
df.sort_values("event_views",ascending=False)[["day", "tickets_sold", "event_views"]].head(1)

       day  tickets_sold  event_views
15  Monday             6           41

In [24]:
df["event_views"].mean()

np.float64(12.294117647058824)

In [25]:
df["event_views"].max()

np.int64(41)

In [26]:
df["event_views"].min()

np.int64(2)

In [27]:
df["event_views"].sum()

np.int64(209)

In [28]:
df["event_views"].count()

np.int64(17)

In [29]:
df.groupby("day")["event_views"].mean()

day
Friday        7.000000
Monday       22.333333
Saturday      8.000000
Sunday       16.666667
Thursday      6.000000
Tuesday       6.666667
Wednesday    15.000000
Name: event_views, dtype: float64

In [30]:
df.groupby("day")["tickets_sold"].mean()

day
Friday       0.000000
Monday       2.666667
Saturday     0.000000
Sunday       3.000000
Thursday     0.500000
Tuesday      0.000000
Wednesday    0.000000
Name: tickets_sold, dtype: float64

In [31]:
average_views_per_day = df.groupby("day")["event_views"].mean()

In [32]:
average_views_per_day.sort_values(ascending=False)

day
Monday       22.333333
Sunday       16.666667
Wednesday    15.000000
Saturday      8.000000
Friday        7.000000
Tuesday       6.666667
Thursday      6.000000
Name: event_views, dtype: float64

In [3]:
print("Important Panda analysis of advertisement data:")

Important Panda analysis of advertisement data:

In [36]:
print("Which entries / days sold over 2 tickets?")

Which entries / days sold over 2 tickets?

In [37]:
over_2_tickets = df[df["tickets_sold"] > 2]
over_2_tickets.sort_values("tickets_sold", ascending=False)

       day  tickets_sold  event_views
7   Sunday             9           35
15  Monday             6           41

In [38]:
print("What was the highest number of tickets sold on a single day?")

What was the highest number of tickets sold on a single day?

In [39]:
highest_number_of_tickets_sold = df.sort_values("tickets_sold",ascending=False)
highest_number_of_tickets_sold[["day", "tickets_sold", "event_views"]].head(1)

      day  tickets_sold  event_views
7  Sunday             9           35

In [40]:
average_views_per_day = df.groupby("day")["event_views"].mean().sort_values(ascending=False)
average_views_per_day

day
Monday       22.333333
Sunday       16.666667
Wednesday    15.000000
Saturday      8.000000
Friday        7.000000
Tuesday       6.666667
Thursday      6.000000
Name: event_views, dtype: float64