In [15]:
print("Data cleaning on a toy datset")

Data cleaning on a toy datset

In [16]:
print("4.1 Finding missing values")

4.1 Finding missing values

In [1]:
import pandas as pd

In [2]:
df = pd.read_csv("../data/toy_dataset_for_cleaning.csv")

In [3]:
df.head()

,event_id,event_name,event_date,venue,capacity,tickets_sold,ticket_price,weather,days_advertised,headliner
0,EVT001,Piece by Piece,21/08/2026,Bonobo Chester,100,92,10.0,Sunny,28,Yes
1,EVT002,House Sessions,05/09/2026,The Warehouse,250,180,12.0,NaN,35,No
2,EVT003,Groove Theory,12/09/2026,Canvas,-180,165,8.0,Cloudy,21,Yes
3,EVT004,After Dark,32/09/2026,District,300,220,15.0,Rain,42,No
4,EVT005,Deep State,19/09/2026,The Loft,150,128,NaN,Sunny,30,Yes

In [4]:
df.shape

(10, 10)

In [5]:
df.info

<bound method DataFrame.info of   event_id      event_name  event_date           venue  capacity  \
0   EVT001  Piece by Piece  21/08/2026  Bonobo Chester       100
1   EVT002  House Sessions  05/09/2026   The Warehouse       250
2   EVT003   Groove Theory  12/09/2026          Canvas      -180
3   EVT004      After Dark  32/09/2026        District       300
4   EVT005      Deep State  19/09/2026        The Loft       150
5   EVT006     Night Shift  26/09/2026     Motion Room       400
6   EVT007       Frequency  03/10/2026  Bonobo chester       100
7   EVT008      Subculture  2026-10-10    Factory Hall       500
8   EVT009   House Society  17/10/2026        The Arch       350
9   EVT001  Piece by Piece  21/08/2026  Bonobo Chester       100

   tickets_sold  ticket_price weather  days_advertised headliner
0            92          10.0   Sunny               28       Yes
1           180          12.0     NaN               35        No
2           165           8.0  Cloudy               21       Yes
3           220          15.0    Rain               42        No
4           128           NaN   Sunny               30       Yes
5           450          18.0    RAIN               18        No
6            75           7.5  Cloudy               14       yes
7           390          20.0   Clear               -5        No
8           -20          12.5     NaN               50       Yes
9            92          10.0   Sunny               28       Yes  >

In [7]:
df.isna()

,event_id,event_name,event_date,venue,capacity,tickets_sold,ticket_price,weather,days_advertised,headliner
0,False,False,False,False,False,False,False,False,False,False
1,False,False,False,False,False,False,False,True,False,False
2,False,False,False,False,False,False,False,False,False,False
3,False,False,False,False,False,False,False,False,False,False
4,False,False,False,False,False,False,True,False,False,False
5,False,False,False,False,False,False,False,False,False,False
6,False,False,False,False,False,False,False,False,False,False
7,False,False,False,False,False,False,False,False,False,False
8,False,False,False,False,False,False,False,True,False,False
9,False,False,False,False,False,False,False,False,False,False

In [8]:
df.isna().sum()

event_id           0
event_name         0
event_date         0
venue              0
capacity           0
tickets_sold       0
ticket_price       1
weather            2
days_advertised    0
headliner          0
dtype: int64

In [9]:
df[df["ticket_price"].isna()]

,event_id,event_name,event_date,venue,capacity,tickets_sold,ticket_price,weather,days_advertised,headliner
4,EVT005,Deep State,19/09/2026,The Loft,150,128,NaN,Sunny,30,Yes

In [10]:
average_price = df["ticket_price"].mean()

average_price

np.float64(12.555555555555555)

In [11]:
df["ticket_price"] = df["ticket_price"].fillna(average_price)

In [12]:
df["ticket_price"].isna().sum()

np.int64(0)

In [13]:
df["weather"] = df["weather"].fillna("Rain")

In [14]:
df["weather"].isna().sum()

np.int64(0)

In [17]:
print("4.2 Identifying impossible values")

4.2 Identifying impossible values

In [18]:
df.describe()

         capacity  tickets_sold  ticket_price  days_advertised
count   10.000000     10.000000     10.000000        10.000000
mean   207.000000    177.200000     12.555556        26.100000
std    194.767668    144.515897      4.092299        15.387224
min   -180.000000    -20.000000      7.500000        -5.000000
25%    100.000000     92.000000     10.000000        18.750000
50%    200.000000    146.500000     12.250000        28.000000
75%    337.500000    210.000000     14.388889        33.750000
max    500.000000    450.000000     20.000000        50.000000

In [19]:
df[df["capacity"] <= 0]

,event_id,event_name,event_date,venue,capacity,tickets_sold,ticket_price,weather,days_advertised,headliner
2,EVT003,Groove Theory,12/09/2026,Canvas,-180,165,8.0,Cloudy,21,Yes

In [20]:
df.loc[df["event_name"] == "Groovy Theory", "capacity"] = 180

In [21]:
df[df["tickets_sold"] > df["capacity"]]

,event_id,event_name,event_date,venue,capacity,tickets_sold,ticket_price,weather,days_advertised,headliner
2,EVT003,Groove Theory,12/09/2026,Canvas,-180,165,8.0,Cloudy,21,Yes
5,EVT006,Night Shift,26/09/2026,Motion Room,400,450,18.0,RAIN,18,No

In [22]:
df[df["ticket_price"] <= 0]

Empty DataFrame
Columns: [event_id, event_name, event_date, venue, capacity, tickets_sold, ticket_price, weather, days_advertised, headliner]
Index: []

In [23]:
df[df["tickets_sold"] < 0]

,event_id,event_name,event_date,venue,capacity,tickets_sold,ticket_price,weather,days_advertised,headliner
8,EVT009,House Society,17/10/2026,The Arch,350,-20,12.5,Rain,50,Yes

In [24]:
df[df["days_advertised"] < 0]

,event_id,event_name,event_date,venue,capacity,tickets_sold,ticket_price,weather,days_advertised,headliner
7,EVT008,Subculture,2026-10-10,Factory Hall,500,390,20.0,Clear,-5,No

In [30]:
print("4.3 Identifying incorrect data types")

4.3 Identifying incorrect data types

In [25]:
df.dtypes

event_id               str
event_name             str
event_date             str
venue                  str
capacity             int64
tickets_sold         int64
ticket_price       float64
weather                str
days_advertised      int64
headliner              str
dtype: object

In [26]:
df["ticket_price"] = pd.to_numeric(df["ticket_price"])

In [27]:
df["ticket_price"] = pd.to_numeric(df["ticket_price"],errors="coerce")

In [28]:
df["event_date"] = pd.to_datetime(df["event_date"],errors="coerce",dayfirst=True)

In [29]:
df.dtypes

event_id                      str
event_name                    str
event_date         datetime64[us]
venue                         str
capacity                    int64
tickets_sold                int64
ticket_price              float64
weather                       str
days_advertised             int64
headliner                     str
dtype: object

In [31]:
df[df["event_date"].isna()]

,event_id,event_name,event_date,venue,capacity,tickets_sold,ticket_price,weather,days_advertised,headliner
3,EVT004,After Dark,NaT,District,300,220,15.0,Rain,42,No
7,EVT008,Subculture,NaT,Factory Hall,500,390,20.0,Clear,-5,No

In [32]:
df.duplicated()

0    False
1    False
2    False
3    False
4    False
5    False
6    False
7    False
8    False
9     True
dtype: bool

In [33]:
df[df.duplicated(keep=False)]

,event_id,event_name,event_date,venue,capacity,tickets_sold,ticket_price,weather,days_advertised,headliner
0,EVT001,Piece by Piece,2026-08-21,Bonobo Chester,100,92,10.0,Sunny,28,Yes
9,EVT001,Piece by Piece,2026-08-21,Bonobo Chester,100,92,10.0,Sunny,28,Yes

In [34]:
df = df.drop_duplicates()

In [35]:
print("4.4 Final Report on data cleaning")

4.4 Final Report on data cleaning

In [36]:
print("Rows:", len(df))
print("Columns:", len(df.columns))
print("Missing values:", df.isna().sum().sum())
print("Duplicate rows:", df.duplicated().sum())
print("Invalid capacities:", (df["capacity"] <= 0).sum())
print("Negative prices:", (df["ticket_price"] < 0).sum())
print("Negative tickets sold:", (df["tickets_sold"] < 0).sum())
print("Negative days advertised:", (df["days_advertised"] < 0).sum())

Rows: 9
Columns: 10
Missing values: 2
Duplicate rows: 0
Invalid capacities: 1
Negative prices: 0
Negative tickets sold: 1
Negative days advertised: 1

In [37]:
oversold = df["tickets_sold"] > df["capacity"]

oversold.sum()

np.int64(2)

In [1]:
print("5.3 Full cleaning process, Refactoring and data analysis with functions")

5.3 Full cleaning process, Refactoring and data analysis with functions

In [1]:
import sys
sys.path.append("../src")

from clean_data import load_data, clean_data

df = load_data("../data/toy_dataset_for_cleaning.csv")

df = clean_data(df)

df

Refactored code for data cleaning and processing using pandas library.
5.1 Refactored code for data cleaning

,event_id,event_name,event_date,venue,capacity,tickets_sold,ticket_price,weather,days_advertised,headliner,sales_exceed_capacity
0,EVT001,Piece by Piece,2026-08-21,Bonobo Chester,100.0,92.0,10.0,Sunny,28.0,Yes,False
1,EVT002,House Sessions,2026-09-05,The Warehouse,250.0,180.0,12.0,<NA>,35.0,No,False
2,EVT003,Groove Theory,2026-09-12,Canvas,NaN,165.0,8.0,Cloudy,21.0,Yes,False
3,EVT004,After Dark,NaT,District,300.0,220.0,15.0,Rain,42.0,No,False
4,EVT005,Deep State,2026-09-19,The Loft,150.0,128.0,NaN,Sunny,30.0,Yes,False
5,EVT006,Night Shift,2026-09-26,Motion Room,400.0,450.0,18.0,Rain,18.0,No,True
6,EVT007,Frequency,2026-10-03,Bonobo chester,100.0,75.0,7.5,Cloudy,14.0,Yes,False
7,EVT008,Subculture,NaT,Factory Hall,500.0,390.0,20.0,Clear,NaN,No,False
8,EVT009,House Society,2026-10-17,The Arch,350.0,NaN,12.5,<NA>,50.0,Yes,False

In [1]:
import sys

sys.path.append("../src")

from clean_data import load_data, clean_data

from analysis import (
    events_over_100_tickets,
    highest_priced_event,
    average_attendance_by_venue,
    add_revenue,
    highest_revenue_event,
    add_capacity_utilisation,
    highest_capacity_utilisation,
    sold_out_events,
    average_ticket_price,
    total_tickets_sold
)

Refactored code for data cleaning and processing using pandas library.
5.1 Refactored code for data cleaning
5.2 Refactored functions for data analysis

In [2]:
df = load_data("../data/toy_dataset_for_cleaning.csv")

df = clean_data(df)

df

,event_id,event_name,event_date,venue,capacity,tickets_sold,ticket_price,weather,days_advertised,headliner,sales_exceed_capacity
0,EVT001,Piece by Piece,2026-08-21,Bonobo Chester,100.0,92.0,10.0,Sunny,28.0,Yes,False
1,EVT002,House Sessions,2026-09-05,The Warehouse,250.0,180.0,12.0,<NA>,35.0,No,False
2,EVT003,Groove Theory,2026-09-12,Canvas,NaN,165.0,8.0,Cloudy,21.0,Yes,False
3,EVT004,After Dark,NaT,District,300.0,220.0,15.0,Rain,42.0,No,False
4,EVT005,Deep State,2026-09-19,The Loft,150.0,128.0,NaN,Sunny,30.0,Yes,False
5,EVT006,Night Shift,2026-09-26,Motion Room,400.0,450.0,18.0,Rain,18.0,No,True
6,EVT007,Frequency,2026-10-03,Bonobo chester,100.0,75.0,7.5,Cloudy,14.0,Yes,False
7,EVT008,Subculture,NaT,Factory Hall,500.0,390.0,20.0,Clear,NaN,No,False
8,EVT009,House Society,2026-10-17,The Arch,350.0,NaN,12.5,<NA>,50.0,Yes,False

In [4]:
events_over_100_tickets(df)

,event_id,event_name,event_date,venue,capacity,tickets_sold,ticket_price,weather,days_advertised,headliner,sales_exceed_capacity
1,EVT002,House Sessions,2026-09-05,The Warehouse,250.0,180.0,12.0,<NA>,35.0,No,False
2,EVT003,Groove Theory,2026-09-12,Canvas,NaN,165.0,8.0,Cloudy,21.0,Yes,False
3,EVT004,After Dark,NaT,District,300.0,220.0,15.0,Rain,42.0,No,False
4,EVT005,Deep State,2026-09-19,The Loft,150.0,128.0,NaN,Sunny,30.0,Yes,False
5,EVT006,Night Shift,2026-09-26,Motion Room,400.0,450.0,18.0,Rain,18.0,No,True
7,EVT008,Subculture,NaT,Factory Hall,500.0,390.0,20.0,Clear,NaN,No,False

In [5]:
highest_priced_event(df)

,event_id,event_name,event_date,venue,capacity,tickets_sold,ticket_price,weather,days_advertised,headliner,sales_exceed_capacity
7,EVT008,Subculture,NaT,Factory Hall,500.0,390.0,20.0,Clear,NaN,No,False

In [6]:
average_attendance_by_venue(df)

venue
Motion Room       450.0
Factory Hall      390.0
District          220.0
The Warehouse     180.0
Canvas            165.0
The Loft          128.0
Bonobo Chester     92.0
Bonobo chester     75.0
The Arch            NaN
Name: tickets_sold, dtype: float64

In [7]:
add_revenue(df)

,event_id,event_name,event_date,venue,capacity,tickets_sold,ticket_price,weather,days_advertised,headliner,sales_exceed_capacity,revenue
0,EVT001,Piece by Piece,2026-08-21,Bonobo Chester,100.0,92.0,10.0,Sunny,28.0,Yes,False,920.0
1,EVT002,House Sessions,2026-09-05,The Warehouse,250.0,180.0,12.0,<NA>,35.0,No,False,2160.0
2,EVT003,Groove Theory,2026-09-12,Canvas,NaN,165.0,8.0,Cloudy,21.0,Yes,False,1320.0
3,EVT004,After Dark,NaT,District,300.0,220.0,15.0,Rain,42.0,No,False,3300.0
4,EVT005,Deep State,2026-09-19,The Loft,150.0,128.0,NaN,Sunny,30.0,Yes,False,NaN
5,EVT006,Night Shift,2026-09-26,Motion Room,400.0,450.0,18.0,Rain,18.0,No,True,8100.0
6,EVT007,Frequency,2026-10-03,Bonobo chester,100.0,75.0,7.5,Cloudy,14.0,Yes,False,562.5
7,EVT008,Subculture,NaT,Factory Hall,500.0,390.0,20.0,Clear,NaN,No,False,7800.0
8,EVT009,House Society,2026-10-17,The Arch,350.0,NaN,12.5,<NA>,50.0,Yes,False,NaN

In [8]:
highest_revenue_event(df)

,event_id,event_name,event_date,venue,capacity,tickets_sold,ticket_price,weather,days_advertised,headliner,sales_exceed_capacity,revenue
5,EVT006,Night Shift,2026-09-26,Motion Room,400.0,450.0,18.0,Rain,18.0,No,True,8100.0

In [9]:
add_capacity_utilisation(df)

,event_id,event_name,event_date,venue,capacity,tickets_sold,ticket_price,weather,days_advertised,headliner,sales_exceed_capacity,capacity_utilisation
0,EVT001,Piece by Piece,2026-08-21,Bonobo Chester,100.0,92.0,10.0,Sunny,28.0,Yes,False,92.000000
1,EVT002,House Sessions,2026-09-05,The Warehouse,250.0,180.0,12.0,<NA>,35.0,No,False,72.000000
2,EVT003,Groove Theory,2026-09-12,Canvas,NaN,165.0,8.0,Cloudy,21.0,Yes,False,NaN
3,EVT004,After Dark,NaT,District,300.0,220.0,15.0,Rain,42.0,No,False,73.333333
4,EVT005,Deep State,2026-09-19,The Loft,150.0,128.0,NaN,Sunny,30.0,Yes,False,85.333333
5,EVT006,Night Shift,2026-09-26,Motion Room,400.0,450.0,18.0,Rain,18.0,No,True,112.500000
6,EVT007,Frequency,2026-10-03,Bonobo chester,100.0,75.0,7.5,Cloudy,14.0,Yes,False,75.000000
7,EVT008,Subculture,NaT,Factory Hall,500.0,390.0,20.0,Clear,NaN,No,False,78.000000
8,EVT009,House Society,2026-10-17,The Arch,350.0,NaN,12.5,<NA>,50.0,Yes,False,NaN

In [10]:
highest_capacity_utilisation(df)

,event_id,event_name,event_date,venue,capacity,tickets_sold,ticket_price,weather,days_advertised,headliner,sales_exceed_capacity,capacity_utilisation
5,EVT006,Night Shift,2026-09-26,Motion Room,400.0,450.0,18.0,Rain,18.0,No,True,112.5

In [11]:
sold_out_events(df)

,event_id,event_name,event_date,venue,capacity,tickets_sold,ticket_price,weather,days_advertised,headliner,sales_exceed_capacity
5,EVT006,Night Shift,2026-09-26,Motion Room,400.0,450.0,18.0,Rain,18.0,No,True

In [12]:
average_ticket_price(df)

np.float64(12.875)

In [13]:
total_tickets_sold(df)

np.float64(1700.0)

In [14]:
df.to_csv(
    "../outputs/cleaned_event_data.csv",
    index=False
)